theme: jekyll-theme-cayman
title: Crypto JBro
description: Cryptocurrency, blockchain, and decentralization simply explained so everybody can understand.  It is time for us to learn together about our new money and new Internet.
